name = "nebula-mail"
compatibility_date = "2024-08-15"

# Pages project config
pages_build_output_dir = "./public"

[vars]
PUBLIC_DOMAIN = ""
MAILGUN_API_BASE = "https://api.mailgun.net"
MAILGUN_DOMAIN = ""
MAILGUN_API_KEY = ""
MAILGUN_SIGNING_KEY = ""
